// Generated by CoffeeScript 1.6.3
(function() {
  var DOM, React, createClass, tag, tags, _fn, _i, _len;

  React = require('react');

  tags = ['div', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ul', 'ol', 'li', 'span', 'a', 'em', 'strong', 'table', 'th', 'tr', 'td', 'nav', 'section', 'article', 'header', 'footer', 'br', 'hr', 'img', 'i', 'button', 'input', 'textarea', 'script'];

  DOM = {};

  _fn = function(tag) {
    return DOM[tag] = function() {
      var params, result;
      params = arguments[0];
      result = React.DOM[tag].apply(React.DOM, arguments);
      return result;
    };
  };
  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    tag = tags[_i];
    _fn(tag);
  }


  /*
  renderComponentToString = (component) ->
      React.renderComponentToString component
   */

  createClass = function(spec) {
    var old_render;
    old_render = spec.render;
    spec.render = function() {
      var result;
      result = old_render.apply(this, arguments);
      if (result) {
        React.Children.map(result.props.children, function(i) {
          if (i) {
            if (i.props.onClick) {
              return console.log(i.props.onClick);
            }
          }
        });
        return result;
      }
    };
    return React.createClass(spec);
  };

  module.exports = {
    DOM: DOM,
    createClass: createClass,
    renderComponentToString: React.renderComponentToString
  };

}).call(this);
